sonar.projectKey=ksurahan-source_hiob-platform
sonar.organization=ksurahan-source
sonar.sources=hiob_platform,pyproject.toml,.github/workflows
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
