"""Hiob agent-native video platform SDK."""
from hiob_platform.client import get_service_client
from hiob_platform.runs import (
    APPROVED_SCRIPT_STATUSES,
    assert_run_script_gate,
    create_production_job,
    create_slot,
    create_text_artifact,
    end_run,
    end_span,
    get_run_script_status,
    maybe_mark_run_produced,
    set_run_script_status,
    start_span,
    update_production_job,
)
from hiob_platform.pronunciation import (
    has_ascii_alpha,
    normalize_korean_pronunciation,
    normalize_script_lines,
    unknown_ascii_terms,
)
from hiob_platform.notify import notify, notify_regen, notify_run_done, notify_run_started
from hiob_platform.role_artifacts import (
    diff_expected_vs_actual,
    expected_artifacts_from_team_leader,
    materialize_role_outputs,
)
from hiob_platform.placement import place_library_video, place_social_proof
from hiob_platform.storage import (
    public_url,
    register_asset_library_item,
    resolve_pool_asset_sha256,
    upload_artifact,
)
from hiob_platform.team import (
    DEFAULT_TEAM_ROLES,
    create_call,
    create_clip,
    create_meeting_note,
    create_team,
    ensure_timeline,
    ensure_track,
    finish_call,
    group_scenes_hold_image,
    load_role,
    point_clips_to_own_beat_image,
    repack_timeline_to_audio,
    split_long_beats_into_subshots,
    sync_caption_positions_from_markers,
    sync_video_positions_from_markers,
    start_call,
    sync_clips_from_slots,
    update_team,
    update_timeline_markers,
    verify_slots_coverage,
)

__all__ = [
    "get_service_client",
    "APPROVED_SCRIPT_STATUSES",
    "assert_run_script_gate",
    "create_production_job",
    "get_run_script_status",
    "maybe_mark_run_produced",
    "set_run_script_status",
    "update_production_job",
    "has_ascii_alpha",
    "normalize_korean_pronunciation",
    "normalize_script_lines",
    "unknown_ascii_terms",
    "start_span",
    "end_span",
    "end_run",
    "create_slot",
    "create_text_artifact",
    "upload_artifact",
    "register_asset_library_item",
    "resolve_pool_asset_sha256",
    "place_library_video",
    "place_social_proof",
    "public_url",
    "notify",
    "notify_run_started",
    "notify_run_done",
    "notify_regen",
    "DEFAULT_TEAM_ROLES",
    "create_team",
    "update_team",
    "create_call",
    "start_call",
    "finish_call",
    "load_role",
    "ensure_timeline",
    "ensure_track",
    "create_clip",
    "create_meeting_note",
    "sync_clips_from_slots",
    "verify_slots_coverage",
    "repack_timeline_to_audio",
    "group_scenes_hold_image",
    "point_clips_to_own_beat_image",
    "split_long_beats_into_subshots",
    "update_timeline_markers",
    "materialize_role_outputs",
    "expected_artifacts_from_team_leader",
    "diff_expected_vs_actual",
]
__version__ = "0.1.0"
